name: darts
channels:
  - anaconda
dependencies:
  - python=3.9
  - pandas
  - pip
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipywidgets
  - pytorch::pytorch 
  - pytorch::torchvision 
  - pytorch::torchaudio 

# To install: 
# conda env create -f environment.yml; conda activate darts; conda install -c conda-forge -y u8darts-all; pip install --upgrade prophet==1.1.4

